server:
  port: 8080

####### resource server configuration properties
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}
      resourceserver:
        jwt:
          issuer-uri: http://keycloak-x:8080/realms/dev
