server:
  port: 8080
  forward-headers-strategy: framework

springdoc:
  use-forward-headers: true

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localstack.lks.com:8080/realms/dev
          user-name-attribute: preferred_username

app:
  keycloak:
    realm: dev

services:
  iam-service:
    base-url: http://nginx
